# Use a base image
FROM nginx:latest

# Copy the application files to the container
COPY ./index.html /usr/share/nginx/html

# Expose the container port
EXPOSE 80

# Set working directory in the container
WORKDIR /usr/share/nginx/html
